### ISSUE TITLE
Bandit - TWAP Based Off First Transaction In A Block Makes Manipulation Risk Free

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-dodo-gsp-judging#80]
Bandit

high

# TWAP Based Off First Transaction In A Block Makes Manipulation Risk Free

## Summary

Widely used TWAP Oracles such as Uniswap v3 only take data from the end of the last transaction in a block. This means that an attacker trying to manipulate it has to leave themselves open to large arbitrage losses because they have to leave the pool reserves imbalanced over a block. Dodo's TWAP instead bases the prices after the first transaction, so an attacker can manipulate it and then reset the price back to the orignal price giving them risk free manipulation that cannot be arbitraged.

## Vulnerability Detail

In the `sellBaseToken` and `sellQuoteToken` functions, `_twapUpdate` is called after the swap logic. When this is the first swap, liquidity or flash loan action of the block, the TWAP is updateed off the reserves after this swap.

The subsequent actions in a block do not update the TWAP, as the `timeElapsed` is `0`:

```solidity
        uint32 timeElapsed = blockTimestamp - _BLOCK_TIMESTAMP_LAST_;
        // if timeElapsed is greater than 0 and the reserves are not 0, update the twap price
        if (timeElapsed > 0 && _BASE_RESERVE_ != 0 && _QUOTE_RESERVE_ != 0) {
            _BASE_PRICE_CUMULATIVE_LAST_ += getMidPrice() * timeElapsed;
```

This is actually different from other TWAP designs such as Uniswap v3 TWAP. In those oracles, the price update is based on the price _at the end of a block_. This makes it resistant manipulation as somebody that wanted to set the TWAP result to an extreme value had to leave it there until the end of the block, in which case it can easily be arbitrage.

In DODO's case, the TWAP can be set to an extreme value simply by bunding these 2 transactions in a flashbots bundle so no arbitrage transactions can be inserted between:

1. making a large swap through the reserves. This changes the recorded `TWAP` price for the time range since the last update.
2. swap back to exactly the original price. This prevents any losses to arbitrage. Since `timeElapsed==0`, the TWAP is not changed by this action 

## Impact

TWAP can be manipulated easily and without risk.

## Code Snippet

https://github.com/sherlock-audit/2023-12-dodo-gsp/blob/main/dodo-gassaving-pool/contracts/GasSavingPool/impl/GSPVault.sol#L86-L97

## Tool used

Manual Review

## Recommendation

Only take prices at the end of a past block. See Uniswap v3's TWAP implementation.

**Comment by Banditx0x** [comment]
Escalate.

Based on the codebase, it can't be known that the TWAP is out of scope. Additionally, the issue is fixed by the sponsor demonstrating it is completely correct.

**Comment by sherlock-admin2** [comment]
> Escalate.
> 
> Based on the codebase, it can't be known that the TWAP is out of scope. Additionally, the issue is fixed by the sponsor demonstrating it is completely correct. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
@Banditx0x I understand the concern and was really borderline for this issue, #39 and #96. But after further review, I think it can be deduced from code logic that TWAP is not used at all within DODO GSP and will not affect price calculations in anyway. The sponsor also confirmed with me that they will be removing it completely.

I do agree more information should have been present during the contest phase.

**Comment by osmanozdemir1** [comment]
I want to point out #96 too, in case of this escalation gets accepted.

Thanks.

**Comment by Banditx0x** [comment]
@nevillehuang alright thank you

**Comment by Czar102** [comment]
I agree with @nevillehuang, this would be a future integration issue (as the codebase being audited is not using the TWAP value).
Planning to reject the escalation and leave the issue as is.

**Comment by Banditx0x** [comment]
Yes I see the reasons for the invalidation. This might be a valid medium in other platforms but under Sherlock's rules it may not qualify as medium.

**Comment by Czar102** [comment]
Result:
Low
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [banditx0x](https://github.com/sherlock-audit/2023-12-dodo-gsp-judging/issues/80/#issuecomment-1890145079): rejected

**Comment by CergyK** [comment]
> We fix this bug in this PR: [DODOEX/dodo-gassaving-pool#13](https://github.com/DODOEX/dodo-gassaving-pool/pull/13)

Fix looks good, could additionally mark TWAP related variables as deprecated for clarity (informational)
